<?php

return [
    'paginate' => 10,
    'success' => 'Action success',
    'input_errors' => [
        'username_required' => 'required',
        'username_max' => 'required',
        'firstname_required' => 'required',
        'firstname_max' => 'required',
        'lastname_required' => 'required',
        'lastname_max' => 'required',
        'address_required' => 'required',
        'address_max' => 'required',
        'phone_required' => 'required',
        'phone_max' => 'required',
        'email_required' => 'required',
        'email_email' => 'required',
        'email_unique' => 'required',
        'email_max' => 'required',
        'birthday_required' => 'required',
        'avatar_max' => 'required',
        'avatar_mimes' => 'required',
        'role_required' => 'required',
        'name_cate_required' => 'required',
        'name_cate_max' => 'max',
        'testname_required' => 'required',
        'testname_max' => 'required',
        'testcode_required' => 'required',
        'testcode_max' => 'required',
        'content_guide_required' => 'required',
        'content_guide_max' => 'required',
        'execute_time_required' => 'required',
        'execute_time_max' => 'required',
        'total_question_required' => 'required',
        'total_question_max' => 'required',
    ]
];
